/**
 * The runner document. It has no markup beyond one inline script: the page is never
 * shown. `{{SCRIPT}}` is replaced by the bundled frame script at build time.
 *
 * The CSP meta tag repeats what the response header already says, minus the directives
 * a meta tag may not carry (`sandbox`, `frame-ancestors`). It matters when the file is
 * served by something other than next.config.ts, such as a static host or a WKWebView.
 * The header stays the authority, because only the header can force the opaque origin.
 */
export const RUNNER_TEMPLATE = `<!doctype html>
<!-- Generated by scripts/build-sandbox.ts. Do not edit. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' blob:; worker-src blob:">
<meta name="robots" content="noindex">
<title>Understory code sandbox</title>
</head>
<body>
<script>{{SCRIPT}}</script>
</body>
</html>
`;

export const SCRIPT_SLOT = '{{SCRIPT}}';

/**
 * Inline script text ends at the first "</script" and changes parsing mode at "<!--".
 * Both can occur inside string literals of the bundle (the harness is one). Inside a
 * JavaScript string or regular expression, "\\/" and "\\!" mean the same as "/" and "!".
 */
export function escapeInlineScript(js: string): string {
  return js.replace(/<\/(script)/gi, '<\\/$1').replace(/<!--/g, '<\\!--');
}

export function renderRunner(script: string): string {
  // A function as the replacement: "$&" and friends in the bundle must stay literal.
  return RUNNER_TEMPLATE.replace(SCRIPT_SLOT, () => escapeInlineScript(script));
}
