export {
  AREA_LEVELS,
  areaLevelOf,
  areaReports,
  focusArea,
  overallLevel,
  placementOutcome,
  thetaForLevel,
  verdictFor,
  type AreaReport,
  type AreaVerdict,
  type ModuleResult,
  type OverallLevel,
  type OverallStage,
  type PlacementOutcome,
} from './outcome';
export {
  placedOut,
  placementKnows,
  recommendPath,
  type Recommendation,
  type RecommendInput,
} from './recommend';
export {
  answerPlacement,
  checkedAreas,
  currentPlacementItem,
  moduleStateOf,
  placementLength,
  placementProgress,
  plannedModules,
  startPlacement,
  undoPlacement,
  type CurrentPlacementItem,
  type ItemRole,
  type ModuleState,
  type PlacementAnswer,
  type PlacementAreaSpec,
  type PlacementItemRef,
  type PlacementMode,
  type PlacementProgress,
  type PlacementScope,
  type PlacementSession,
  type PlannedModule,
} from './session';
