/**
 * Builds the static sandbox artefacts from their single sources of truth:
 *
 *   public/sandbox/harness.v1.js         the harness string, for JavaScriptCore on iOS
 *   public/sandbox/runner.v1.html        the runner document with the frame script inlined
 *   public/sandbox/react-runtime.v1.js   React, a worker DOM and Testing Library, for tsx
 *   public/sandbox/react-playground.v1.js  React and react-dom, for React playgrounds
 *
 * All are committed, so the app builds without this step, and a unit test
 * (tests/unit/adapters/sandbox/build.test.ts) fails when they are stale.
 *
 *   pnpm exec tsx scripts/build-sandbox.ts           write the files
 *   pnpm exec tsx scripts/build-sandbox.ts --check   exit 1 if they would change
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { build } from 'esbuild';
import { renderRunner } from '../src/adapters/sandbox/frame/runner-template';
import { HARNESS_V1 } from '../src/core/running/harness';

// Resolved from the working directory, like the other scripts: pnpm runs them from the
// repository root, and tsx loads this file as CommonJS, where import.meta is absent.
const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, 'public/sandbox');

export interface SandboxArtefact {
  file: string;
  content: string;
}

export async function buildSandboxArtefacts(): Promise<SandboxArtefact[]> {
  const bundle = await build({
    entryPoints: [path.join(ROOT, 'src/adapters/sandbox/frame/frame-main.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    // The harness promises ES2020; the frame script need not be newer than that either.
    target: 'es2020',
    minify: true,
    legalComments: 'none',
    charset: 'ascii',
    alias: { '@': path.join(ROOT, 'src') },
    logLevel: 'silent',
  });
  const script = bundle.outputFiles[0]?.text;
  if (script === undefined) throw new Error('esbuild produced no output for the frame script');

  return [
    { file: path.join(OUT_DIR, 'harness.v1.js'), content: HARNESS_V1 },
    { file: path.join(OUT_DIR, 'runner.v1.html'), content: renderRunner(script.trimEnd()) },
    { file: path.join(OUT_DIR, 'react-runtime.v1.js'), content: await buildReactRuntime() },
    { file: path.join(OUT_DIR, 'react-playground.v1.js'), content: await buildReactPlayground() },
  ];
}

/**
 * The React runtime of tsx runs (src/adapters/sandbox/react-runtime/). The development
 * build of React, on purpose: it gives `act` to tests and warns about missing keys, and
 * a learner should see those warnings. Class names are kept because pretty-format and
 * Testing Library read `constructor.name` to recognise DOM nodes.
 */
export async function buildReactRuntime(): Promise<string> {
  const dir = path.join(ROOT, 'src/adapters/sandbox/react-runtime');
  const bundle = await build({
    entryPoints: [path.join(dir, 'runtime.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    minify: true,
    keepNames: true,
    legalComments: 'none',
    charset: 'ascii',
    define: { 'process.env.NODE_ENV': '"development"' },
    inject: [path.join(dir, 'polyfills.ts')],
    alias: { '@': path.join(ROOT, 'src') },
    banner: { js: '/* Understory React runtime v1. Generated by scripts/build-sandbox.ts. */' },
    logLevel: 'silent',
  });
  const script = bundle.outputFiles[0]?.text;
  if (script === undefined) throw new Error('esbuild produced no output for the React runtime');
  return script;
}

/**
 * The React of React playgrounds (src/adapters/sandbox/react-playground/). The development
 * build, as for tsx runs: its errors are sentences rather than numbered codes, and it
 * warns about a list without keys, which the preview shows. The page inlines this text
 * in a script element, so it must never contain a closing script tag.
 */
export async function buildReactPlayground(): Promise<string> {
  const bundle = await build({
    entryPoints: [path.join(ROOT, 'src/adapters/sandbox/react-playground/runtime.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    minify: true,
    legalComments: 'none',
    charset: 'ascii',
    define: { 'process.env.NODE_ENV': '"development"' },
    alias: { '@': path.join(ROOT, 'src') },
    banner: {
      js: '/* Understory React playground runtime v1. Generated by scripts/build-sandbox.ts. */',
    },
    logLevel: 'silent',
  });
  const script = bundle.outputFiles[0]?.text;
  if (script === undefined) throw new Error('esbuild produced no output for the React playground');
  if (/<\/script/i.test(script)) throw new Error('The React playground runtime contains </script');
  return script;
}

async function isCurrent(artefact: SandboxArtefact): Promise<boolean> {
  try {
    return (await readFile(artefact.file, 'utf8')) === artefact.content;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const artefacts = await buildSandboxArtefacts();
  let stale = 0;
  for (const artefact of artefacts) {
    const name = path.relative(ROOT, artefact.file);
    if (await isCurrent(artefact)) {
      console.log(`current  ${name}`);
      continue;
    }
    stale += 1;
    if (check) {
      console.error(`stale    ${name}`);
      continue;
    }
    await mkdir(path.dirname(artefact.file), { recursive: true });
    await writeFile(artefact.file, artefact.content);
    console.log(`written  ${name} (${Math.round(artefact.content.length / 1024)} KB)`);
  }
  if (check && stale > 0) {
    console.error('Run: pnpm exec tsx scripts/build-sandbox.ts');
    process.exitCode = 1;
  }
}

// Run only as a script. The unit test imports buildSandboxArtefacts without side effects.
if (path.basename(process.argv[1] ?? '').startsWith('build-sandbox')) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  });
}
