/**
 * Writes the files UnderstoryRunner embeds, each from the source the web uses, so the
 * phone runs the bytes the browser and the CI gate run:
 *
 *   harness.v1.js          copied from public/sandbox/harness.v1.js
 *   react-runtime.v1.js    copied from public/sandbox/react-runtime.v1.js (tsx runs)
 *   python-harness.v1.py   PYTHON_HARNESS_V1 from src/core/running/python-harness.ts
 *   sucrase.v1.js          the installed `sucrase` package, bundled for JavaScriptCore
 *   pyodide.v1.json        version, size and SHA-256 of the five Pyodide files, and of the
 *                          wheels numpy, pandas and pydantic need, per package in load order
 *   react-playground.v1.js copied from public/sandbox/react-playground.v1.js (jsx playgrounds)
 *   core-kit.v1.js         the web's page builder, checks, grading and SQL verdict from
 *                          src/core, bundled for JavaScriptCore (`CoreKit`)
 *   sql-host.v1.js         the web's WorkerSqlEngine, bundled for the SQL web view's page
 *   sql-engine.v1.js       the web's SQL worker (scripts/build-sql.ts `buildEngine`)
 *   pglite.v1.json         version, size and SHA-256 of PGlite's three data files
 *
 * All are committed, so `swift build` needs no Node. Pyodide, its wheels and PGlite's
 * wasm are not embedded: they are downloaded once and checked against the manifests
 * (docs/SANDBOX.md, "Python" and "SQL", "On iOS").
 *
 * Run from the repository root:
 *   pnpm exec tsx ios/UnderstoryKit/Scripts/build-resources.ts           write
 *   pnpm exec tsx ios/UnderstoryKit/Scripts/build-resources.ts --check   exit 1 if stale
 */
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { build, type Plugin } from 'esbuild';
import { PYODIDE_FILES, PYODIDE_VERSION } from '../../../src/adapters/pyodide/assets';
import { ensureWheels } from '../../../src/adapters/pyodide/wheels';
import { PYTHON_HARNESS_V1 } from '../../../src/core/running/python-harness';
import { PYTHON_PACKAGES } from '../../../src/core/running/python-packages';
import { buildEngine, PGLITE_FILES, pgliteDir, pgliteVersion } from '../../../scripts/build-sql';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'ios/UnderstoryKit/Sources/UnderstoryRunner/Resources');
const requireFromRoot = createRequire(path.join(ROOT, 'package.json'));

async function sucrase(): Promise<string> {
  const version = (requireFromRoot('sucrase/package.json') as { version: string }).version;
  const bundle = await build({
    stdin: {
      contents: `import { transform } from 'sucrase';\nglobalThis.__sucrase = { transform: transform, version: ${JSON.stringify(version)} };`,
      resolveDir: ROOT,
      loader: 'js',
    },
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'neutral',
    mainFields: ['main'],
    target: 'es2020',
    minify: true,
    legalComments: 'none',
    charset: 'ascii',
    banner: {
      js: `/* sucrase ${version}. Generated by ios/UnderstoryKit/Scripts/build-resources.ts. */`,
    },
    logLevel: 'silent',
  });
  const text = bundle.outputFiles[0]?.text;
  if (text === undefined) throw new Error('esbuild produced no output for sucrase');
  return text;
}

const digest = (data: Uint8Array): string => createHash('sha256').update(data).digest('hex');

async function pinned(dir: string, names: readonly string[]) {
  const files: Record<string, { bytes: number; sha256: string }> = {};
  for (const name of [...names].sort()) {
    const data = await readFile(path.join(dir, name));
    files[name] = { bytes: data.length, sha256: digest(data) };
  }
  return files;
}

async function pyodideManifest(): Promise<string> {
  const dir = path.dirname(requireFromRoot.resolve('pyodide'));
  const files = await pinned(dir, Object.values(PYODIDE_FILES));
  // The wheels come from the cache the web build fills (src/adapters/pyodide/wheels.ts),
  // each already checked against the lock file's SHA-256.
  const packages: Record<string, string[]> = {};
  const wheels: Record<string, { bytes: number; sha256: string }> = {};
  for (const name of PYTHON_PACKAGES) {
    const ensured = await ensureWheels([name], { root: ROOT });
    packages[name] = ensured.files.map((file) => file.fileName);
    Object.assign(wheels, await pinned(ensured.dir, packages[name]));
  }
  const sortedWheels = Object.fromEntries(
    Object.entries(wheels).sort(([a], [b]) => a.localeCompare(b)),
  );
  return `${JSON.stringify({ version: PYODIDE_VERSION, files, packages, wheels: sortedWheels }, null, 2)}\n`;
}

async function pgliteManifest(): Promise<string> {
  const files = await pinned(pgliteDir(ROOT), PGLITE_FILES);
  return `${JSON.stringify({ version: pgliteVersion(ROOT), files }, null, 2)}\n`;
}

/**
 * zod re-exports every locale as a namespace, which keeps all forty in a bundle although
 * only English is configured. Nothing here reads another, so the namespace holds English
 * alone: about 60 KB less per bundle, with the same messages.
 */
const englishOnly: Plugin = {
  name: 'zod-english-only',
  setup(builder) {
    builder.onResolve({ filter: /locales\/index\.js$/ }, (args) =>
      args.importer.includes(`${path.sep}zod${path.sep}`)
        ? { path: path.join(args.resolveDir, args.path), namespace: 'zod-locales' }
        : undefined,
    );
    builder.onLoad({ filter: /.*/, namespace: 'zod-locales' }, (args) => ({
      contents: "export { default as en } from './en.js';",
      resolveDir: path.dirname(args.path),
      loader: 'js',
    }));
  },
};

/** An entry written inline, bundled for JavaScriptCore or a web view page. */
async function bundle(contents: string, banner: string, target = 'es2020'): Promise<string> {
  const result = await build({
    stdin: { contents, resolveDir: ROOT, loader: 'ts' },
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'neutral',
    mainFields: ['module', 'main'],
    target,
    minify: true,
    legalComments: 'none',
    charset: 'ascii',
    alias: { '@': path.join(ROOT, 'src') },
    plugins: [englishOnly],
    banner: { js: `/* ${banner} Generated by ios/UnderstoryKit/Scripts/build-resources.ts. */` },
    logLevel: 'silent',
  });
  const text = result.outputFiles[0]?.text;
  if (text === undefined) throw new Error(`esbuild produced no output for ${banner}`);
  return text;
}

/**
 * What CoreKit calls: the playground's page builder, the check judge and the grade, and
 * the SQL verdict and grade. The web's own functions, so a verdict on the phone is the
 * browser's. JSON in, JSON out, so Swift never touches a JavaScript object.
 */
const CORE_KIT = `
import { buildPlaygroundDocument, evaluateChecks, parsePlaygroundMessage } from '@/core/playground';
import { gradePlayground } from '@/core/grading/grade';
import { gradeSql, sqlVerdict } from '@/core/sql';
const json = (f) => (input) => JSON.stringify(f(JSON.parse(input)));
globalThis.__understoryCore = {
  page: json(({ files, options }) => buildPlaygroundDocument(files, options)),
  message: json((data) => parsePlaygroundMessage(data)),
  checks: json(({ checks, facts }) => {
    const results = evaluateChecks(checks, facts);
    return { results, grade: gradePlayground(checks, results) };
  }),
  sql: json(({ learner, expected, checks }) => {
    const verdict = sqlVerdict(learner, expected, checks);
    return { verdict, grade: gradeSql(verdict) };
  }),
};
`;

/**
 * The SQL web view's page script: the browser's WorkerSqlEngine, one worker, its budgets
 * and its never-reject contract, with the worker served from the page's own scheme.
 */
const SQL_HOST = `
import { WorkerSqlEngine } from '@/adapters/sql/worker-engine';
const engine = new WorkerSqlEngine({
  createWorker: async () => new Worker('understory-sql://sql/engine.js', { type: 'module', name: 'sql' }),
});
window.understorySqlRun = (request) => engine.run(request).then((report) => JSON.stringify(report));
`;

async function artefacts(): Promise<{ name: string; content: string }[]> {
  const sandbox = (name: string) => readFile(path.join(ROOT, 'public/sandbox', name), 'utf8');
  return [
    { name: 'harness.v1.js', content: await sandbox('harness.v1.js') },
    { name: 'react-runtime.v1.js', content: await sandbox('react-runtime.v1.js') },
    { name: 'python-harness.v1.py', content: PYTHON_HARNESS_V1 },
    { name: 'sucrase.v1.js', content: await sucrase() },
    { name: 'pyodide.v1.json', content: await pyodideManifest() },
    { name: 'react-playground.v1.js', content: await sandbox('react-playground.v1.js') },
    { name: 'core-kit.v1.js', content: await bundle(CORE_KIT, 'src/core playground and sql.') },
    { name: 'sql-host.v1.js', content: await bundle(SQL_HOST, 'WorkerSqlEngine.') },
    { name: 'sql-engine.v1.js', content: (await buildEngine(ROOT)).code },
    { name: 'pglite.v1.json', content: await pgliteManifest() },
  ];
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const { name, content } of await artefacts()) {
    const file = path.join(OUT, name);
    const current = await readFile(file, 'utf8').catch(() => null);
    if (current === content) {
      console.log(`current  ${name}`);
      continue;
    }
    stale += 1;
    if (check) {
      console.error(`stale    ${name}`);
      continue;
    }
    await mkdir(OUT, { recursive: true });
    await writeFile(file, content);
    console.log(`written  ${name} (${Math.round(content.length / 1024)} KB)`);
  }
  if (check && stale > 0) {
    console.error('Run: ios/UnderstoryKit/Scripts/sync-resources.sh');
    process.exitCode = 1;
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
